version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
    - 6.1.3
  - dependency-name: actionpack
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
